// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/lug": {
    params: {};
  };
  "/docs/:category/:subject?/:name": {
    params: {
      "category": string;
      "subject"?: string;
      "name": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/lug" | "/docs/:category/:subject?/:name" | "/*";
  };
  "app/LayoutShell.tsx": {
    id: "app/LayoutShell";
    page: "/" | "/dashboard" | "/lug" | "/docs/:category/:subject?/:name" | "/*";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "routes/Dashboard.tsx": {
    id: "routes/Dashboard";
    page: "/dashboard";
  };
  "components/LugCalculator/LugCalculator.tsx": {
    id: "components/LugCalculator/LugCalculator";
    page: "/lug";
  };
  "routes/DynamicMdxPage.tsx": {
    id: "routes/DynamicMdxPage";
    page: "/docs/:category/:subject?/:name";
  };
  "pages/Errors/NothingFoundBackground.tsx": {
    id: "pages/Errors/NothingFoundBackground";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./../src/root.tsx");
  "app/LayoutShell": typeof import("./../src/app/LayoutShell.tsx");
  "pages/home": typeof import("./../src/pages/home.tsx");
  "routes/Dashboard": typeof import("./../src/routes/Dashboard.tsx");
  "components/LugCalculator/LugCalculator": typeof import("./../src/components/LugCalculator/LugCalculator.tsx");
  "routes/DynamicMdxPage": typeof import("./../src/routes/DynamicMdxPage.tsx");
  "pages/Errors/NothingFoundBackground": typeof import("./../src/pages/Errors/NothingFoundBackground.tsx");
};